Question 1

Given three integer arrays arr1, arr2 and arr3 **sorted** in **strictly increasing** order, return a sorted array of **only** the integers that appeared in **all** three arrays.

**Example 1:**

Input: arr1 = [1,2,3,4,5], arr2 = [1,2,5,7,9], arr3 = [1,3,4,5,8]

Output: [1,5]

**Explanation:** Only 1 and 5 appeared in the three arrays.


In [1]:
def array_intersection(arr1, arr2,arr3): 
  arr1.sort()
  arr2.sort()
  arr3.sort()
  final =[]
  for ele in arr1:
    if (ele in arr2) and (ele in arr3):
      final.append(ele)
    else:
      continue  
  
  return final          
  

In [2]:
#creating a array of random numbers of length 10
import numpy as np
arr1 = [1,2,3,4,5,6]
arr2 = [3,6,9,10,14,19]
arr3 = [1,3,4,6,7,12]
result = array_intersection(arr1, arr2, arr3)
print(result)

[3, 6]


<aside>
💡 **Question 2**

Given two **0-indexed** integer arrays nums1 and nums2, return *a list* answer *of size* 2 *where:*

- answer[0] *is a list of all **distinct** integers in* nums1 *which are **not** present in* nums2*.*
- answer[1] *is a list of all **distinct** integers in* nums2 *which are **not** present in* nums1.

**Note** that the integers in the lists may be returned in **any** order.

**Example 1:**

**Input:** nums1 = [1,2,3], nums2 = [2,4,6]

**Output:** [[1,3],[4,6]]

**Explanation:**

For nums1, nums1[1] = 2 is present at index 0 of nums2, whereas nums1[0] = 1 and nums1[2] = 3 are not present in nums2. Therefore, answer[0] = [1,3].

For nums2, nums2[0] = 2 is present at index 1 of nums1, whereas nums2[1] = 4 and nums2[2] = 6 are not present in nums2. Therefore, answer[1] = [4,6].

</aside>

In [3]:
def array_unique(arr1,arr2):
  arr1.sort()
  arr2.sort()
  main_lst =[]
  arr1_lst =[]
  arr2_lst =[]
  for ele in arr1:
    if ele not in arr2:
      arr1_lst.append(ele)
    else:
      continue
  main_lst.append(arr1_lst)
  for ele in arr2:
    if ele not in arr1:
      arr2_lst.append(ele)
    else:
      continue
  main_lst.append(arr2_lst)
  return main_lst

In [4]:
#creating a array of random numbers of length 10
import numpy as np
arr1 = [1,2,3,4,5,6]
arr2 = [1,3,4,7,10,13]
result = array_unique(arr1,arr2)
print(result)

[[2, 5, 6], [7, 10, 13]]



💡 **Question 3**

Given a 2D integer array matrix, return *the **transpose** of* matrix.

The **transpose** of a matrix is the matrix flipped over its main diagonal, switching the matrix's row and column indices.

**Example 1:**

Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]

Output: [[1,4,7],[2,5,8],[3,6,9]]



In [5]:
def transpose(matrix):
    row =len(matrix)
    col = len(matrix[0])
    
    row_lst=[]
    for i in range(col):
      col_lst=[]
      for j in range(row):
        col_lst.append(matrix[j][i])
      row_lst.append(col_lst)
    
    return row_lst

In [6]:
#creating a array of random numbers of length 10
import numpy as np
matrix = [[1,2,3],[4,5,6],[7,8,9]]
result = transpose(matrix)
print(result)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


**Question 4**

Given an integer array nums of 2n integers, group these integers into n pairs (a1, b1), (a2, b2), ..., (an, bn) such that the sum of min(ai, bi) for all i is **maximized**. Return *the maximized sum*.

**Example 1:**

Input: nums = [1,4,3,2]

Output: 4

**Explanation:** All possible pairings (ignoring the ordering of elements) are:

1. (1, 4), (2, 3) -> min(1, 4) + min(2, 3) = 1 + 2 = 3

2. (1, 3), (2, 4) -> min(1, 3) + min(2, 4) = 1 + 2 = 3

3. (1, 2), (3, 4) -> min(1, 2) + min(3, 4) = 1 + 3 = 4

So the maximum possible sum is 4.


In [7]:
def max_summation(nums): 
  nums = list(nums) 
  pair = []
  max_sum = 0
  idx_lst = []
  for i,n in enumerate(nums):
    if i not in idx_lst:  
      diff={}
      # print(np.where(nums==i))
      for j,m in enumerate(nums[i+1:]):
        diff[abs(n-m)] = j+i+1
      #print(diff)
      lowest_val = (min(diff.keys()), diff[min(diff.keys())])
      idx = lowest_val[1]
      

      max_sum += min(n, nums[idx])
      idx_lst.append(idx)

  return max_sum
  

In [8]:
#creating a array of random numbers of length 10
import numpy as np

nums = np.random.randint(-50,50,size=(10,))
print(nums)
result = max_summation(nums)
print(result)

[-12  -1   1 -22   3  -3 -25 -35  20  -8]
-82


**Question 5**

You have n coins and you want to build a staircase with these coins. The staircase consists of k rows where the ith row has exactly i coins. The last row of the staircase **may be** incomplete.

Given the integer n, return *the number of **complete rows** of the staircase you will build*.



In [9]:
def staircase(n):
  i=0
  sum = 0
  while sum <= n and (n-sum)>i:
    i+=1
    sum +=i
    # n-=i

  return i

In [10]:
coins = int(input("Enter the no. of coins:"))
result = staircase(coins)
print(result)

Enter the no. of coins:14
4


*Question 6**

Given an integer array nums sorted in **non-decreasing** order, return *an array of **the squares of each number** sorted in non-decreasing order*.

**Example 1:**

Input: nums = [-4,-1,0,3,10]

Output: [0,1,9,16,100]

**Explanation:** After squaring, the array becomes [16,1,0,9,100].
After sorting, it becomes [0,1,9,16,100]


In [11]:
def square_sort(nums):
  nums.sort()
  sqr_lst=[]
  for ele in nums:
    sqr_lst.append(ele*ele)
  return sqr_lst

In [12]:
import numpy as np
nums = [1,1,4,5,6,5,4,2,7,7]
result = square_sort(nums)
print(result)

[1, 1, 4, 16, 16, 25, 25, 36, 49, 49]


**Question 7**

You are given an m x n matrix M initialized with all 0's and an array of operations ops, where ops[i] = [ai, bi] means M[x][y] should be incremented by one for all 0 <= x < ai and 0 <= y < bi.

Count and return *the number of maximum integers in the matrix after performing all the operations*

**Example 1:**

![q4.jpg](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/4d0890d0-7bc7-4f59-be8e-352d9f3c1c52/q4.jpg)

**Input:** m = 3, n = 3, ops = [[2,2],[3,3]]

**Output:** 4

**Explanation:** The maximum integer in M is 2, and there are four of it in M. So return 4.


In [32]:
def maximum_integers(m, n, ops):
  l=len(ops)
  matrix = np.zeros([m,n])
  for t,ele in enumerate(ops):
    

    if ele[0]>m or ele[1]>n:
      return print(" ops size should be less than or equal to matrix size")
    else:

      for i in range(ele[0]):
        
        if i < ele[0]:

          for j in range(ele[1]):  
            if j < ele[1]:
              matrix[i][j]+=1
            
        else:
          for j in range(ele[1]): 
            if j < ele[1]: 
              matrix[i][j]+=1

  return matrix

In [33]:
import numpy as np
m=3
n=3
ops=[[2,2],[3,3]]
result = maximum_integers(m, n, ops)
print(result)

[[2. 2. 1.]
 [2. 2. 1.]
 [1. 1. 1.]]


*Question 8**

Given the array nums consisting of 2n elements in the form [x1,x2,...,xn,y1,y2,...,yn].

*Return the array in the form* [x1,y1,x2,y2,...,xn,yn].

**Example 1:**

**Input:** nums = [2,5,1,3,4,7], n = 3

**Output:** [2,3,5,4,1,7]

**Explanation:** Since x1=2, x2=5, x3=1, y1=3, y2=4, y3=7 then the answer is [2,3,5,4,1,7].


In [40]:
def rearrange_arr(nums):
    l = len(nums)
    half = int(l/2)
    rearrange_lst=[]
    for i in range(half):
      rearrange_lst.append(nums[i])
      rearrange_lst.append(nums[i+half])
      
    return rearrange_lst
    

In [41]:
import numpy as np
nums= [4,6,8,3,4,2,0,1]
result =rearrange_arr(nums)
print(result)

[4, 4, 6, 2, 8, 0, 3, 1]
