Question 1

Given an integer array nums of length n and an integer target, find three integers
in nums such that the sum is closest to the target.
Return the sum of the three integers.

You may assume that each input would have exactly one solution.

Example 1:
Input: nums = [-1,2,1,-4], target = 1
Output: 2

Explanation: The sum that is closest to the target is 2. (-1 + 2 + 1 = 2).

In [ ]:
def sum_of_three(nums, target): 
  nums.sort()
  sum = 0
  l = len(nums)
  k = l-1
  sum_diff =[]
  idx_lst = []
  for i in range(l-1):
    for j in range(i+1, l-1):
      if k!=j:
        sum = nums[i] + nums[j] + nums[k]
        sum_diff.append(abs(sum-target))
        idx_lst.append((i,j,k))
        if sum == target:
          return sum
        elif sum < target:
          j+=1
        else:
          k-=1
      else:
        break
  # print(sum_diff)
  idx = sum_diff.index(min(sum_diff))    
  sum = nums[idx_lst[idx][0]] + nums[idx_lst[idx][1]] + nums[idx_lst[idx][2]] 
 
  return sum
  

In [ ]:
#creating a array of random numbers of length 10
import numpy as np

arr_size = np.random.randint(3,10,size=(1,))[0]
arr = np.random.randint(-50,50,size=(arr_size,))
print(arr)
n = int(input('Enter the target number:'))
result = sum_of_three(arr,n)
print(result)

[ 23  -7 -42 -16  14 -46 -28  39]
Enter the target number:22
21


Question 2

Given an array nums of n integers, return an array of all the unique quadruplets
[nums[a], nums[b], nums[c], nums[d]] such that:
           ● 0 <= a, b, c, d < n
           ● a, b, c, and d are distinct.
           ● nums[a] + nums[b] + nums[c] + nums[d] == target

You may return the answer in any order.

Example 1:
Input: nums = [1,0,-1,0,-2,2], target = 0
Output: [[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]

In [ ]:
def quadruplets(nums, target):
  nums.sort()
  sum = 0
  l = len(nums)
  result =[]
  
  for a in range(l-3):
    if a == 0:
      
      for b in range(a+1, l-1):
        if b == 1:
          c = b+1
          d = l-1
        elif b > 1 and nums[b]==nums[b-1]:
          continue
        while d < b:
          sum = nums[a] + nums[b] + nums[c] + nums[d] 
          
          if sum == target:
            result.append([nums[a], nums[b], nums[c], nums[d]])
            while c < d and nums[c] == nums[c+1]:
              c += 1
            while c < d and nums[d] == nums[d-1]:
              d -= 1
            c +=1
            d -=1
          elif sum < target:
            c+=1
          else:
            d-=1

        
    elif a > 0 and nums[a]==nums[a-1]:
      continue
 
  return sum
  

In [ ]:
#creating a array of random numbers of length 10
import numpy as np

arr_size = np.random.randint(6,10,size=(1,))[0]
arr = np.random.randint(-50,50,size=(arr_size,))
print(arr)
n = int(input('Enter the target number:'))
result = quadruplets(arr,n)
print(result)

[ 45  26   6  48 -48   9 -10]
Enter the target number:31
0


<aside>
💡 **Question 3**

A permutation of an array of integers is an arrangement of its members into a
sequence or linear order.

For example, for arr = [1,2,3], the following are all the permutations of arr:
[1,2,3], [1,3,2], [2, 1, 3], [2, 3, 1], [3,1,2], [3,2,1].

The next permutation of an array of integers is the next lexicographically greater
permutation of its integer. More formally, if all the permutations of the array are
sorted in one container according to their lexicographical order, then the next
permutation of that array is the permutation that follows it in the sorted container.

If such an arrangement is not possible, the array must be rearranged as the
lowest possible order (i.e., sorted in ascending order).

● For example, the next permutation of arr = [1,2,3] is [1,3,2].
● Similarly, the next permutation of arr = [2,3,1] is [3,1,2].
● While the next permutation of arr = [3,2,1] is [1,2,3] because [3,2,1] does not
have a lexicographical larger rearrangement.

Given an array of integers nums, find the next permutation of nums.
The replacement must be in place and use only constant extra memory.

**Example 1:**
Input: nums = [1,2,3]
Output: [1,3,2]

</aside>

In [ ]:
def nextPermutation(nums):
    n = len(nums)
    i = n - 2
    while i >= 0 and nums[i] >= nums[i + 1]:
        i -= 1
    if i >= 0:
        j = n - 1
        while j >= 0 and nums[i] >= nums[j]:
            j -= 1
        nums[i], nums[j] = nums[j], nums[i]
    nums[i + 1:] = reversed(nums[i + 1:])

In [ ]:
#creating a array of random numbers of length 10
import numpy as np
nums = [1,2,3]
nextPermutation(nums)
print(nums)

[1, 3, 2]


Question 4


Given a sorted array of distinct integers and a target value, return the index if the
target is found. If not, return the index where it would be if it were inserted in
order.

You must write an algorithm with O(log n) runtime complexity.

Example 1:
Input: nums = [1,3,5,6], target = 5
Output: 2

In [ ]:
def findTarget(arr, target):
  start= 0
  end =  len(arr) - 1
  while start <= end:
      mid = (start + end) // 2
      if arr[mid] == target:
          return mid
      elif arr[mid] < target:
          start = mid + 1
      else:
          end = mid - 1
  return f"Number should be index:{start}"


In [ ]:
import numpy as np

A= np.random.randint(-50,50,size=(10,))
num = np.random.choice(A,1, replace = False)[0]
A= np.sort(A)
print(A)
findTarget(A,16)

[-47 -43 -36 -33 -20  -3  -1  13  31  46]


'Number should be index:8'

<aside>
💡 **Question 5**

You are given a large integer represented as an integer array digits, where each
digits[i] is the ith digit of the integer. The digits are ordered from most significant
to least significant in left-to-right order. The large integer does not contain any
leading 0's.

Increment the large integer by one and return the resulting array of digits.

**Example 1:**
Input: digits = [1,2,3]
Output: [1,2,4]

**Explanation:** The array represents the integer 123.
Incrementing by one gives 123 + 1 = 124.
Thus, the result should be [1,2,4].

</aside>

In [ ]:
integer = str(input('Enter a large integer='))
print(integer)
int_lst = integer.split(',')
int_lst[-1] = str(int(int_lst[-1])+1)
integer = ''.join(int_lst)
print(integer)

Enter a large integer=567
567
568


Question 6

Given a non-empty array of integers nums, every element appears twice except
for one. Find that single one.

You must implement a solution with a linear runtime complexity and use only
constant extra space.

Example 1:
Input: nums = [2,2,1]
Output: 1

In [ ]:
def single_one(nums):
  for ele in nums:
    if nums.count(ele)==1:
      return ele
    else:
      continue
  

In [ ]:
import numpy as np
nums = [1,1,4,5,6,5,4,2,7,7]
result = single_one(nums)
print(result)

6


Question 7

You are given an inclusive range [lower, upper] and a sorted unique integer array
nums, where all elements are within the inclusive range.

A number x is considered missing if x is in the range [lower, upper] and x is not in
nums.

Return the shortest sorted list of ranges that exactly covers all the missing
numbers. That is, no element of nums is included in any of the ranges, and each
missing number is covered by one of the ranges.

Example 1:
Input: nums = [0,1,3,50,75], lower = 0, upper = 99
Output: [[2,2],[4,49],[51,74],[76,99]]

Explanation: The ranges are:
[2,2]
[4,49]
[51,74]
[76,99]

In [52]:
def find_ranges(nums, n_range):
  nums.sort()
  nums = list(nums)
  range_lst =[]
  l =len(nums)
  print(l)
  if nums[0]!=n_range[0]:
      range_lst.append([n_range[0],nums[0]])

  for i in range(0,l):
    if (nums[i] != nums[-1]) and (nums[i]-nums[i+1] > 1):
      range_lst.append([nums[i]+1,nums[i+1]-1])

  if nums[-1]!=n_range[1]:
    range_lst.append([nums[-1],n_range[1]])    

  return range_lst

In [ ]:
import numpy as np
arr_size = np.random.randint(3,10,size=(1,))[0]
arr = np.random.randint(0,50,size=(arr_size,))
print(arr)
r = [0,99]
result = find_ranges(arr, r)
print(result)

Question 8

Given an array of meeting time intervals where intervals[i] = [starti, endi],
determine if a person could attend all meetings.

Example 1:
Input: intervals = [[0,30],[5,10],[15,20]]
Output: false

In [50]:
def canAttendMeetings(intervals):
    intervals.sort(key=lambda x: x[0])
    for i in range(1, len(intervals)):
        if intervals[i][0] < intervals[i-1][1]:
            return False
    return True
    

In [ ]:
import numpy as np
intervals = [[0,30],[5,10],[15,20]] 
canAttendMeetings(intervals)