<aside>
💡 **Question 1**
Given an integer array nums of 2n integers, group these integers into n pairs (a1, b1), (a2, b2),..., (an, bn) such that the sum of min(ai, bi) for all i is maximized. Return the maximized sum.

**Example 1:**
Input: nums = [1,4,3,2]
Output: 4

**Explanation:** All possible pairings (ignoring the ordering of elements) are:

1. (1, 4), (2, 3) -> min(1, 4) + min(2, 3) = 1 + 2 = 3
2. (1, 3), (2, 4) -> min(1, 3) + min(2, 4) = 1 + 2 = 3
3. (1, 2), (3, 4) -> min(1, 2) + min(3, 4) = 1 + 3 = 4
So the maximum possible sum is 4
</aside>

In [ ]:
def max_summation(nums): 
  nums = list(nums) 
  pair = []
  max_sum = 0
  idx_lst = []
  for i,n in enumerate(nums):
    if i not in idx_lst:  
      diff={}
      # print(np.where(nums==i))
      for j,m in enumerate(nums[i+1:]):
        diff[abs(n-m)] = j+i+1
      #print(diff)
      lowest_val = (min(diff.keys()), diff[min(diff.keys())])
      idx = lowest_val[1]
      

      max_sum += min(n, nums[idx])
      idx_lst.append(idx)

  return max_sum
  

In [ ]:
#creating a array of random numbers of length 10
import numpy as np

nums = np.random.randint(-50,50,size=(10,))
print(nums)
result = max_summation(nums)
print(result)

[ 30  33  17 -12  12 -28 -30  46  12   5]
8


Question 2

Alice has n candies, where the ith candy is of type candyType[i]. Alice noticed that she started to gain weight, so she visited a doctor. 

The doctor advised Alice to only eat n / 2 of the candies she has (n is always even). Alice likes her candies very much, and she wants to eat the maximum number of different types of candies while still following the doctor's advice. 

Given the integer array candyType of length n, return the maximum number of different types of candies she can eat if she only eats n / 2 of them.

Example 1:
Input: candyType = [1,1,2,2,3,3]
Output: 3

Explanation: Alice can only eat 6 / 2 = 3 candies. Since there are only 3 types, she can eat one of each type.

In [ ]:
def max_candies(candies):

  n = len(candies)
  max_candies = n//2
  candy_types = set(candies)
  num_candy_types = len(candy_types)
  return min(num_candy_types, max_candies)

In [ ]:
import numpy as np

nums = np.random.randint(0,50,size=(20,))
print(nums)
result = max_candies(nums)
print(result)

[42  3 42 29 23  7 39 16 23  1 27 32 30 28 28  1 40  7 34 17]
10


Question3 

We define a harmonious array as an array where the difference between its maximum value
and its minimum value is exactly 1.

Given an integer array nums, return the length of its longest harmonious subsequence
among all its possible subsequences.

A subsequence of an array is a sequence that can be derived from the array by deleting some or no elements without changing the order of the remaining elements.

Example 1:
Input: nums = [1,3,2,2,5,2,3,7]
Output: 5

Explanation: The longest harmonious subsequence is [3,2,2,2,3].

In [ ]:
def longest_subseq(nums):
  l = list(nums)
  
  for i in nums: 
    unique_lst = []
    for ele in l:
      if ele not in unique_lst:
        unique_lst.append(ele)
    
    large = max(unique_lst)
    small = min(unique_lst)
    if large-small == 1:
      return len(l)
    elif large-small == 0:
      return 1
    else:
      diff = large-small
      if l.count(large) >= l.count(small):
        while l.count(small):
          l.remove(small)
      else:
        while l.count(large):
          l.remove(large)
      

In [ ]:
#creating a array of random numbers of length 10
import numpy as np

nums = np.random.randint(0,50,size=(10,))
print(nums)
result = longest_subseq(nums)
print(result)

[42 12  1  6 11 37 12 16  9 13]
3


Question 4

You have a long flowerbed in which some of the plots are planted, and some are not.
However, flowers cannot be planted in adjacent plots.
Given an integer array flowerbed containing 0's and 1's, where 0 means empty and 1 means not empty, and an integer n, return true if n new flowers can be planted in the flowerbed without violating the no-adjacent-flowers rule and false otherwise.

Example 1:
Input: flowerbed = [1,0,0,0,1], n = 1
Output: true

In [ ]:
def flower_feasible(arr, n):
  l = list(arr)
  flowerbed_counts = len(l)
  if flowerbed_counts <= 2:
    return False
  elif n > (flowerbed_counts)//2:
    return False
  else:
    zero_counts = 0
    possible_flowerbeds = 0

    for i in range(flowerbed_counts):
      if l[i]==0:
        zero_counts+=1
        if (zero_counts == flowerbed_counts) and (zero_counts % 2 ==1):
          possible_flowerbeds = zero_counts // 2 + 1
        elif (zero_counts == flowerbed_counts) and (zero_counts % 2 ==0):
          possible_flowerbeds = zero_counts // 2
        elif ((zero_counts >= 3) and (zero_counts % 2 ==1) and (l[i]==l[-1])) or ((zero_counts >= 3) and (zero_counts % 2 ==1) and (l[i+1]==1)):
          possible_flowerbeds += zero_counts // 2
        else:
          continue
      else:
        zero_counts = 0    
      
    if possible_flowerbeds == n:
      return True     
    else:
      return False


In [ ]:
import numpy as np

arr = np.random.randint(0,2,size=(10,))
n = np.random.randint(1,6,size=(1,))[0]
print(arr)
print(n)
flower_feasible(arr,n)

[1 0 1 1 1 0 0 0 1 0]
1


True

Question 5

Given an integer array nums, find three numbers whose product is maximum and return the maximum product.

Example 1:
Input: nums = [1,2,3]
Output: 6

In [ ]:
def max_product(nums):
  l = list(nums)
  if (0 in l) and len(l) == 3:
    max_prod = 0
  
  else:
    max_prod = 1
    for i in range(3):
      maxm = max(l)
      max_prod *= maxm
      l.remove(maxm)

  return max_prod  

In [ ]:
import numpy as np
arr_size = np.random.randint(3,10,size=(1,))[0]
arr = np.random.randint(0,50,size=(arr_size,))
print(arr)
product = max_product(arr)
print(product)

[15 31 34]
15810


Question 6

Given an array of integers nums which is sorted in ascending order, and an integer target,
write a function to search target in nums. If target exists, then return its index. Otherwise,
return -1.

You must write an algorithm with O(log n) runtime complexity.

Input: nums = [-1,0,3,5,9,12], target = 9
Output: 4

Explanation: 9 exists in nums and its index is 4

In [60]:
def find_target(arr, target):
  start= 0
  end =  len(arr) - 1
  while start <= end:
      mid = (start + end) // 2
      if arr[mid] == target:
          return mid
      elif arr[mid] < target:
          start = mid + 1
      else:
          end = mid - 1
  return -1

In [61]:
import numpy as np
arr_size = np.random.randint(3,10,size=(1,))[0]
arr = np.random.randint(0,50,size=(arr_size,))
arr.sort()
print(arr)
n = int(input('Enter the target number to find in array:'))
find_target(arr,n)

[20 22 34 40 48 49]
Enter the target number to find in array:47


-1

Question 7

An array is monotonic if it is either monotone increasing or monotone decreasing.

An array nums is monotone increasing if for all i <= j, nums[i] <= nums[j]. An array nums is
monotone decreasing if for all i <= j, nums[i] >= nums[j].

Given an integer array nums, return true if the given array is monotonic, or false otherwise.

Example 1:
Input: nums = [1,2,2,3]
Output: true

In [83]:
def is_monotonic(nums):
  nums = list(nums)
  minm = min(nums)
  maxm = max(nums)
  
  if nums[0]==maxm:
    nums.sort()
    
  for ele in nums:
    if ele ==nums[0]:
      if ele == minm:
        continue
      else:
        return False
    elif nums[nums.index(ele)-1] <= ele:
      continue

  return True    
    

In [85]:
import numpy as np
arr_size = np.random.randint(3,10,size=(1,))[0]
arr = np.random.randint(0,50,size=(arr_size,))
print(arr)
res = input('want sorted array (y/n):')
if res == 'y':
  res_2 = input('Sorted in increasing or decreasing (i/d):')
  if res_2 == 'i':
    arr.sort()
  elif res_2 == 'd':
    arr[::-1].sort()
print(arr)
print(is_monotonic(arr))

[34 32 43  8 48 31 40  2]
want sorted array (y/n):y
Sorted in increasing or decreasing (i/d):d
[48 43 40 34 32 31  8  2]
True


Question 8

You are given an integer array nums and an integer k.

In one operation, you can choose any index i where 0 <= i < nums.length and change nums[i] to nums[i] + x where x is an integer from the range [-k, k]. You can apply this operation at most once for each index i.

The score of nums is the difference between the maximum and minimum elements in nums.

Return the minimum score of nums after applying the mentioned operation at most once for each index in it.

Example 1:
Input: nums = [1], k = 0
Output: 0

Explanation: The score is max(nums) - min(nums) = 1 - 1 = 0.

In [88]:
def min_score(nums,k):
  l = list(nums)
  maxm = max(l)
  minm = min(l)
  score = maxm-minm
  if score == 0:
    return 0
  
  else:
    for i in range(len(l)):
      if l[i] != maxm and (maxm-l[i]) <= k:
        l[i]+= (maxm-l[i])
      elif l[i] != maxm and (maxm-l[i]) > k:
        l[i]+= k
      else:
        continue
    score = max(l) - min(l)

    return score  
      
      

    

In [89]:
import numpy as np
arr_size = np.random.randint(3,10,size=(1,))[0]
arr = np.random.randint(0,50,size=(arr_size,))
print(arr)
k = int(input('Enter the k value for range [-k,k]:'))
print(min_score(arr,k))

[40 12 25 34 27 40  0 48]
Enter the k value for range [-k,k]:12
36
