 **Question 1**

A permutation perm of n + 1 integers of all the integers in the range [0, n] can be represented as a string s of length n where:

- s[i] == 'I' if perm[i] < perm[i + 1], and
- s[i] == 'D' if perm[i] > perm[i + 1].

Given a string s, reconstruct the permutation perm and return it. If there are multiple valid permutations perm, return **any of them**.

**Example 1:**

**Input:** s = "IDID"

**Output:**

[0,4,1,3,2]


In [ ]:
def permutation_perm(strg): 
  
  l = len(strg)
  lst = list(range(l+1))
  print(lst)
  permutation_perm=[]
  for c in strg:
    if c=="I" and strg.index(c)==0:
      ele = max(lst)
      while ele==max(lst) or (ele in permutation_perm):
        ele=random.choice(lst)
    elif c=="D" and strg.index(c)==0:
      while ele==min(lst) or (ele in permutation_perm):
        ele = random.choice(lst)
    elif (c=="I" and strg.index(c)==-1) or (c=="D" and strg.index(c)==-1):
      while ele in permutation_perm:
        ele = random.choice(lst)
    elif c=='I':
      while ele != min(lst):
        ele = random.choice(lst)
    else:
      while ele != max(lst):
        ele= random.choice(lst)

    permutation_perm.append(ele)
    lst.remove(ele)
  return permutation_perm

In [ ]:
#creating a array of random numbers of length 10
import numpy as np
import random
strg = 'IDDID'
result = permutation_perm(strg)
print(result)

[0, 1, 2, 3, 4, 5]
[3, 5, 4, 1, 2]


**Question 2**

You are given an m x n integer matrix matrix with the following two properties:

- Each row is sorted in non-decreasing order.
- The first integer of each row is greater than the last integer of the previous row.

Given an integer target, return true *if* target *is in* matrix *or* false *otherwise*.

You must write a solution in O(log(m * n)) time complexity.

**Example 1:**
**Input:** matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3

**Output:** true

In [ ]:
def searchMatrix(matrix, target):
    m, n = len(matrix), len(matrix[0])
    left, right = 0, m * n - 1
    while left <= right:
        mid = (left + right) // 2
        row, col = divmod(mid, n)
        if matrix[row][col] == target:
            return True
        elif matrix[row][col] < target:
            left = mid + 1
        else:
            right = mid - 1
    return False

In [ ]:
import math

matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]]
target = 34
result = searchMatrix(matrix, target)
print(result)

True


*Question 3**

Given an array of integers arr, return *true if and only if it is a valid mountain array*.

Recall that arr is a mountain array if and only if:

- arr.length >= 3
- There exists some i with 0 < i < arr.length - 1 such that:
    - arr[0] < arr[1] < ... < arr[i - 1] < arr[i]
    - arr[i] > arr[i + 1] > ... > arr[arr.length - 1]
    
**Example 1:**

**Input:** arr = [2,1]

**Output:**

false

In [ ]:
def mountain_array(arr):
  arr = list(arr)
  count = 0
  for i in range(len(arr)):
    if i < (len(arr)-1) and arr[i] < arr[i+1]:
      if count == 0:
        continue
      else:
        return False
    elif i < (len(arr)-1) and arr[i] > arr[i+1]:
      count = 1
      continue
    elif i== len(arr)-1:
      return True
    else:
      return False
      
  return True

In [ ]:
import numpy as np
arr = [1,3,4,5,6,7,5,4,2,0]
result = mountain_array(arr)
print(result)

True


**Question 4**

Given a binary array nums, return *the maximum length of a contiguous subarray with an equal number of* 0 *and* 1.

**Example 1:**

**Input:** nums = [0,1]

**Output:** 2

**Explanation:**

[0, 1] is the longest contiguous subarray with an equal number of 0 and 1.


In [1]:
def contiguous_subarray(nums):
  idx_lst=[]
  # l = len(nums)
  zero_counts=0
  one_counts=0
  for i,ele in enumerate(nums):
    if ele==0:
      zero_counts +=1
    else:
      one_counts +=1
    
    if zero_counts==one_counts:
      idx_lst.append(i)
      
    else:
      continue  

  max_length = max(idx_lst)+1
  return max_length    

In [2]:
#creating a array of random numbers of length 10
import numpy as np
nums = [1,1,1,0,0,1,0,0,1,0,1]
result = contiguous_subarray(nums)
print(result)

10


**Question 5**

The **product sum** of two equal-length arrays a and b is equal to the sum of a[i] * b[i] for all 0 <= i < a.length (**0-indexed**).

- For example, if a = [1,2,3,4] and b = [5,2,3,1], the **product sum** would be 1*5 + 2*2 + 3*3 + 4*1 = 22.

Given two arrays nums1 and nums2 of length n, return *the **minimum product sum** if you are allowed to **rearrange** the **order** of the elements in* nums1.

**Example 1:**

**Input:** nums1 = [5,3,4,2], nums2 = [4,2,2,5]

**Output:** 40

**Explanation:**

We can rearrange nums1 to become [3,5,4,2]. The product sum of [3,5,4,2] and [4,2,2,5] is 3*4 + 5*2 + 4*2 + 2*5 = 40.


In [7]:
def product_sum(arr1, arr2):
  l=len(arr1)
  arr1.sort()
  arr2.sort(reverse=True)
  sum = 0
  for i in range(l):
    sum += arr1[i]*arr2[i]

  return sum

In [10]:
arr1=[5,3,4,2]
arr2 = [4,2,2,5]

result =product_sum(arr1, arr2)
print(result)

40


**Question 6**

An integer array original is transformed into a **doubled** array changed by appending **twice the value** of every element in original, and then randomly **shuffling** the resulting array.

Given an array changed, return original *if* changed *is a **doubled** array. If* changed *is not a **doubled** array, return an empty array. The elements in* original *may be returned in **any** order*.

**Example 1:**

**Input:** changed = [1,3,4,2,6,8]

**Output:** [1,3,4]

**Explanation:** One possible original array could be [1,3,4]:

- Twice the value of 1 is 1 * 2 = 2.
- Twice the value of 3 is 3 * 2 = 6.
- Twice the value of 4 is 4 * 2 = 8.

Other original arrays could be [4,3,1] or [3,1,4].


In [11]:
def doubled_array(nums):
  nums.sort()
  nums = list(nums)
  l = len(nums)
  for ele in nums:
    if ele*2 in nums:
      nums.remove(ele*2)
      continue
    else:
      return [] 
    
  return np.array(nums)
    

In [12]:
import numpy as np
nums= [2,4,8,4,10,14,6,5,7,3]
result =doubled_array(nums)
print(result)

[2 3 4 5 7]


**Question 7**

Given a positive integer n, generate an n x n matrix filled with elements from 1 to n2 in spiral order.

**Example 1:**
**Input:** n = 3

**Output:** [[1,2,3],[8,9,4],[7,6,5]]

In [14]:
def generateMatrix(n: int):
    matrix = [[0 for i in range(n)] for j in range(n)]
    row_start, row_end = 0, n - 1
    col_start, col_end = 0, n - 1
    num = 1
    while row_start <= row_end and col_start <= col_end:
        for i in range(col_start, col_end + 1):
            matrix[row_start][i] = num
            num += 1
        row_start += 1
        for i in range(row_start, row_end + 1):
            matrix[i][col_end] = num
            num += 1
        col_end -= 1
        if row_start <= row_end:
            for i in range(col_end, col_start - 1, -1):
                matrix[row_end][i] = num
                num += 1
            row_end -= 1
        if col_start <= col_end:
            for i in range(row_end, row_start - 1, -1):
                matrix[i][col_start] = num
                num += 1
            col_start += 1
    return matrix

In [15]:
n = 3
result = generateMatrix(n)
print(result)

[[1, 2, 3], [8, 9, 4], [7, 6, 5]]


**Question 8**

Given two [sparse matrices](https://en.wikipedia.org/wiki/Sparse_matrix) mat1 of size m x k and mat2 of size k x n, return the result of mat1 x mat2. You may assume that multiplication is always possible.

**Example 1:**
**Input:** mat1 = [[1,0,0],[-1,0,3]], mat2 = [[7,0,0],[0,0,0],[0,0,1]]

**Output:**

[[7,0,0],[-7,0,3]]

In [16]:
import numpy as np
from scipy.sparse import csr_matrix

# define mat1 and mat2 as csr matrices
mat1 = csr_matrix([[1, 0, 0], [-1, 0, 3]])
mat2 = csr_matrix([[7, 0, 0], [0, 0, 0], [0, 0, 1]])

# perform matrix multiplication
result = mat1.dot(mat2)

# convert result to a dense matrix for printing
print(result.todense())

[[ 7  0  0]
 [-7  0  3]]
