Q1. <aside>
💡 **Q1.** Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

**Example:**
Input: nums = [2,7,11,15], target = 9
Output0 [0,1]

**Explanation:** Because nums[0] + nums[1] == 9, we return [0, 1][

</aside>

In [ ]:
#creating a array of random numbers of length 10
import numpy as np
nums = np.random.randint(-50,50,size=(10,))
print(nums)


[ 26 -25 -29 -43 -41 -18  15 -42 -10 -45]


In [ ]:
# creating the target number randomly from the array 'nums'
num_1,num_2 = np.random.choice(nums,2, replace = False)
target = num_1 + num_2
print(f'number 1: {num_1}')
print(f'number 2: {num_2}')
print(f'Target num: {target}')

number 1: 1
number 2: -35
Target num: -34


In [ ]:
#creating a dictionary to store the difference as key & index as value
diff_dict = {}
for i,num in enumerate(nums):
  diff = target - num
  if diff in nums:
    print(f'Two numbers are at index: {list(nums).index(diff)} and {i}')
    break 
  else:
    diff_dict[diff]=i
  

Two numbers are at index: 7 and 0


<aside>
💡 **Q2.** Given an integer array nums and an integer val, remove all occurrences of val in nums in-place. The order of the elements may be changed. Then return the number of elements in nums which are not equal to val.

Consider the number of elements in nums which are not equal to val be k, to get accepted, you need to do the following things:

- Change the array nums such that the first k elements of nums contain the elements which are not equal to val. The remaining elements of nums are not important as well as the size of nums.
- Return k.

**Example :**
Input: nums = [3,2,2,3], val = 3
Output: 2, nums = [2,2,_*,_*]

**Explanation:** Your function should return k = 2, with the first two elements of nums being 2. It does not matter what you leave beyond the returned k (hence they are underscores)[

</aside>

In [ ]:
#creating a function to do the above task
def remove_val(arr, val):
  l = list(arr)
  if val in l:
    for ele in l:
      if ele == val:
        l.remove(ele)
        l.append('_')
    print(l)
  else:
    print(f'value {val} is not found in array {l}')

    


In [ ]:
A= np.random.randint(-50,50,size=(10,))
num = 4
remove_val(A, num)

[6, 88, 8, 3, 6, -1, 7, 0, '_', '_']


<aside>
💡 **Q3.** Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.

You must write an algorithm with O(log n) runtime complexity.

**Example 1:**
Input: nums = [1,3,5,6], target = 5

Output: 2

</aside>

In [13]:
def findTarget(arr, target):
  start= 0
  end =  len(arr) - 1
  while start <= end:
      mid = (start + end) // 2
      if arr[mid] == target:
          return mid
      elif arr[mid] < target:
          start = mid + 1
      else:
          end = mid - 1
  return f"Number should be index:{start}"

In [14]:
import numpy as np

A= np.random.randint(-50,50,size=(10,))
num = np.random.choice(A,1, replace = False)[0]
A= np.sort(A)
print(A)
findTarget(A,16)

[-39 -36 -28 -20 -15 -14 -10  12  17  22]


'Number should be index:8'

<aside>
💡 **Q4.** You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer. The digits are ordered from most significant to least significant in left-to-right order. The large integer does not contain any leading 0's.

Increment the large integer by one and return the resulting array of digits.

**Example 1:**
Input: digits = [1,2,3]
Output: [1,2,4]

**Explanation:** The array represents the integer 123.

Incrementing by one gives 123 + 1 = 124.
Thus, the result should be [1,2,4].

</aside>

In [18]:
integer = str(input('Enter a large integer=2'))
print(integer)
int_lst = integer.split(',')
int_lst[-1] = str(int(int_lst[-1])+1)
integer = ''.join(int_lst)
print(integer)

Enter a large integer=23455
23455
23456


<aside>
💡 **Q5.** You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, and two integers m and n, representing the number of elements in nums1 and nums2 respectively.

Merge nums1 and nums2 into a single array sorted in non-decreasing order.

The final sorted array should not be returned by the function, but instead be stored inside the array nums1. To accommodate this, nums1 has a length of m + n, where the first m elements denote the elements that should be merged, and the last n elements are set to 0 and should be ignored. nums2 has a length of n.

**Example 1:**
Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3
Output: [1,2,2,3,5,6]

**Explanation:** The arrays we are merging are [1,2,3] and [2,5,6].
The result of the merge is [1,2,2,3,5,6] with the underlined elements coming from nums1.

</aside>

In [61]:
response_1 = input('Enter integer elements of array separeted by space like 3 5 66 7 4 = ')
num1 = response_1.split(' ')
# num1 = map(int(),num1)
num1 = [int(n) for n in num1]
num1.sort()
response_2 = input('Enter integer elements of array separeted by space like 3 5 66 7 4 = ')
num2 = response_2.split(' ')
num2 = [int(m) for m in num2]
num2.sort()


Enter integer elements of array separeted by space like 3 5 66 7 4 = 2 3 5 6 7 8 9 11 33 0 4 2
Enter integer elements of array separeted by space like 3 5 66 7 4 = 4 62 2 6 8


In [62]:
print(num1)
print(num2)

[0, 2, 2, 3, 4, 5, 6, 7, 8, 9, 11, 33]
[2, 4, 6, 8, 62]


In [63]:
for ele in num2:
  num1.append(ele)
num1.sort()

In [64]:
print(num1)

[0, 2, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8, 9, 11, 33, 62]


<aside>
💡 **Q6.** Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.

**Example 1:**
Input: nums = [1,2,3,1]

Output: true

</aside>

In [77]:

def duplicate_find(nums):
  l = list(nums)
  length = len(l)
  count = 0
  for ele in l:
    idx = l.index(ele)
    if ele in l[idx+1:]:
      return True
    
    else:
      count+=1
  
  if count == length:
    return False


In [79]:
nums = np.random.randint(-50,50,size=(10,))
print(nums)
duplicate_find(nums)

[-24  14 -27 -40  34  28 -24  -4 -19 -24]


True

<aside>
💡 **Q7.** Given an integer array nums, move all 0's to the end of it while maintaining the relative order of the nonzero elements.

Note that you must do this in-place without making a copy of the array.

**Example 1:**
Input: nums = [0,1,0,3,12]
Output: [1,3,12,0,0]

</aside>

In [80]:
def moveZeroes(nums):
    
    i = 0
    for j in range(len(nums)):
        if nums[j] != 0:
            nums[i], nums[j] = nums[j], nums[i]
            i += 1

In [81]:
nums = [1,0,3,21,4,6,4,0,4]
moveZeroes(nums)

In [82]:
print(nums)

[1, 3, 21, 4, 6, 4, 4, 0, 0]


<aside>
💡 **Q8.** You have a set of integers s, which originally contains all the numbers from 1 to n. Unfortunately, due to some error, one of the numbers in s got duplicated to another number in the set, which results in repetition of one number and loss of another number.

You are given an integer array nums representing the data status of this set after the error.

Find the number that occurs twice and the number that is missing and return them in the form of an array.

**Example 1:**
Input: nums = [1,2,2,4]
Output: [2,3]

</aside>

In [84]:
def findErrorNums(nums):
    n = len(nums)
    nums_set = set(nums)
    duplicate = sum(nums) - sum(nums_set)
    missing = n * (n + 1) // 2 - sum(nums_set)
    return [duplicate, missing]

In [87]:
nums = [1,2,3,4,5,5,7]
findErrorNums(nums)

[5, 6]